package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/carlosf/k8s-pod-manager/graph/model"
	"github.com/carlosf/k8s-pod-manager/internal/services"
)

// RestartPod is the resolver for the restartPod field.
// Refactored to follow SOLID principles with proper validation, error handling, and audit logging
func (r *mutationResolver) RestartPod(ctx context.Context, namespace string, name string, user *string) (*model.RestartPodResponse, error) {
	// Input validation using injected validator
	if err := r.getValidator().ValidateNamespace(namespace); err != nil {
		r.getAuditLogger().LogMutation(ctx, "restartPod", namespace, name, getUserOrDefault(user), false, err.Error())
		return nil, r.getErrorHandler().HandleValidationError(err, "namespace")
	}

	if err := r.getValidator().ValidatePodName(name); err != nil {
		r.getAuditLogger().LogMutation(ctx, "restartPod", namespace, name, getUserOrDefault(user), false, err.Error())
		return nil, r.getErrorHandler().HandleValidationError(err, "name")
	}

	if err := r.getValidator().ValidateUserInput(user); err != nil {
		r.getAuditLogger().LogMutation(ctx, "restartPod", namespace, name, getUserOrDefault(user), false, err.Error())
		return nil, r.getErrorHandler().HandleValidationError(err, "user")
	}

	executedBy := getUserOrDefault(user)
	result, err := r.getPodService().RestartPod(ctx, namespace, name, executedBy)
	if err != nil {
		r.getAuditLogger().LogMutation(ctx, "restartPod", namespace, name, executedBy, false, err.Error())
		return nil, r.getErrorHandler().HandleServiceError(err, "restartPod")
	}

	// Build response using safe type assertions
	response := &model.RestartPodResponse{
		Pod:       name,
		Namespace: namespace,
	}

	// Safe type assertion with error handling
	if message, ok := result["message"].(string); ok {
		response.Message = message
	} else {
		response.Message = "Pod restart initiated"
	}

	if t, ok := result["type"].(string); ok {
		response.Type = t
	}
	if d, ok := result["deployment"].(string); ok && d != "" {
		response.Deployment = &d
	}
	if s, ok := result["statefulset"].(string); ok && s != "" {
		response.Statefulset = &s
	}
	if c, ok := result["controller"].(string); ok && c != "" {
		response.Controller = &c
	}
	if w, ok := result["warning"].(string); ok && w != "" {
		response.Warning = &w
	}

	// Log successful operation
	r.getAuditLogger().LogMutation(ctx, "restartPod", namespace, name, executedBy, true, "")

	return response, nil
}

// DeletePod is the resolver for the deletePod field.
// Refactored with validation, error handling, and audit logging
func (r *mutationResolver) DeletePod(ctx context.Context, namespace string, name string, user *string) (*model.DeletePodResponse, error) {
	// Input validation
	if err := r.getValidator().ValidateNamespace(namespace); err != nil {
		r.getAuditLogger().LogMutation(ctx, "deletePod", namespace, name, getUserOrDefault(user), false, err.Error())
		return nil, r.getErrorHandler().HandleValidationError(err, "namespace")
	}

	if err := r.getValidator().ValidatePodName(name); err != nil {
		r.getAuditLogger().LogMutation(ctx, "deletePod", namespace, name, getUserOrDefault(user), false, err.Error())
		return nil, r.getErrorHandler().HandleValidationError(err, "name")
	}

	if err := r.getValidator().ValidateUserInput(user); err != nil {
		r.getAuditLogger().LogMutation(ctx, "deletePod", namespace, name, getUserOrDefault(user), false, err.Error())
		return nil, r.getErrorHandler().HandleValidationError(err, "user")
	}

	executedBy := getUserOrDefault(user)
	err := r.getPodService().DeletePod(ctx, namespace, name, executedBy)
	if err != nil {
		r.getAuditLogger().LogMutation(ctx, "deletePod", namespace, name, executedBy, false, err.Error())
		return nil, r.getErrorHandler().HandleServiceError(err, "deletePod")
	}

	// Log successful operation
	r.getAuditLogger().LogMutation(ctx, "deletePod", namespace, name, executedBy, true, "")

	return &model.DeletePodResponse{
		Message:   "Pod deleted successfully",
		Pod:       name,
		Namespace: namespace,
	}, nil
}

// ScaleDeployment is the resolver for the scaleDeployment field.
// Refactored with comprehensive validation and error handling
func (r *mutationResolver) ScaleDeployment(ctx context.Context, namespace string, name string, input model.ScaleInput, user *string) (*model.ScaleResponse, error) {
	// Input validation
	if err := r.getValidator().ValidateNamespace(namespace); err != nil {
		r.getAuditLogger().LogMutation(ctx, "scaleDeployment", namespace, name, getUserOrDefault(user), false, err.Error())
		return nil, r.getErrorHandler().HandleValidationError(err, "namespace")
	}

	if err := r.getValidator().ValidatePodName(name); err != nil {
		r.getAuditLogger().LogMutation(ctx, "scaleDeployment", namespace, name, getUserOrDefault(user), false, err.Error())
		return nil, r.getErrorHandler().HandleValidationError(err, "name")
	}

	if err := r.getValidator().ValidateScaleInput(input); err != nil {
		r.getAuditLogger().LogMutation(ctx, "scaleDeployment", namespace, name, getUserOrDefault(user), false, err.Error())
		return nil, r.getErrorHandler().HandleValidationError(err, "input")
	}

	if err := r.getValidator().ValidateUserInput(user); err != nil {
		r.getAuditLogger().LogMutation(ctx, "scaleDeployment", namespace, name, getUserOrDefault(user), false, err.Error())
		return nil, r.getErrorHandler().HandleValidationError(err, "user")
	}

	executedBy := getUserOrDefault(user)
	result, err := r.getPodService().ScaleDeployment(ctx, namespace, name, int32(input.Replicas), executedBy)
	if err != nil {
		r.getAuditLogger().LogMutation(ctx, "scaleDeployment", namespace, name, executedBy, false, err.Error())
		return nil, r.getErrorHandler().HandleServiceError(err, "scaleDeployment")
	}

	// Build response with safe type assertions
	response := &model.ScaleResponse{
		Namespace: namespace,
	}

	// Safe type assertions with defaults
	if message, ok := result["message"].(string); ok {
		response.Message = message
	} else {
		response.Message = "Deployment scaled successfully"
	}

	if prevReplicas, ok := result["previous_replicas"].(int32); ok {
		response.PreviousReplicas = int(prevReplicas)
	}

	if newReplicas, ok := result["new_replicas"].(int32); ok {
		response.NewReplicas = int(newReplicas)
	}

	if action, ok := result["action"].(string); ok {
		response.Action = action
	} else {
		response.Action = "scale"
	}

	if d, ok := result["deployment"].(string); ok && d != "" {
		response.Deployment = &d
	}

	// Log successful operation
	r.getAuditLogger().LogMutation(ctx, "scaleDeployment", namespace, name, executedBy, true, "")

	return response, nil
}

// ScaleStatefulSet is the resolver for the scaleStatefulSet field.
// Refactored with validation and proper error handling
func (r *mutationResolver) ScaleStatefulSet(ctx context.Context, namespace string, name string, input model.ScaleInput, user *string) (*model.ScaleResponse, error) {
	// Input validation
	if err := r.getValidator().ValidateNamespace(namespace); err != nil {
		r.getAuditLogger().LogMutation(ctx, "scaleStatefulSet", namespace, name, getUserOrDefault(user), false, err.Error())
		return nil, r.getErrorHandler().HandleValidationError(err, "namespace")
	}

	if err := r.getValidator().ValidatePodName(name); err != nil {
		r.getAuditLogger().LogMutation(ctx, "scaleStatefulSet", namespace, name, getUserOrDefault(user), false, err.Error())
		return nil, r.getErrorHandler().HandleValidationError(err, "name")
	}

	if err := r.getValidator().ValidateScaleInput(input); err != nil {
		r.getAuditLogger().LogMutation(ctx, "scaleStatefulSet", namespace, name, getUserOrDefault(user), false, err.Error())
		return nil, r.getErrorHandler().HandleValidationError(err, "input")
	}

	if err := r.getValidator().ValidateUserInput(user); err != nil {
		r.getAuditLogger().LogMutation(ctx, "scaleStatefulSet", namespace, name, getUserOrDefault(user), false, err.Error())
		return nil, r.getErrorHandler().HandleValidationError(err, "user")
	}

	executedBy := getUserOrDefault(user)
	result, err := r.getPodService().ScaleStatefulSet(ctx, namespace, name, int32(input.Replicas), executedBy)
	if err != nil {
		r.getAuditLogger().LogMutation(ctx, "scaleStatefulSet", namespace, name, executedBy, false, err.Error())
		return nil, r.getErrorHandler().HandleServiceError(err, "scaleStatefulSet")
	}

	// Build response with safe type assertions
	response := &model.ScaleResponse{
		Namespace: namespace,
	}

	if message, ok := result["message"].(string); ok {
		response.Message = message
	} else {
		response.Message = "StatefulSet scaled successfully"
	}

	if prevReplicas, ok := result["previous_replicas"].(int32); ok {
		response.PreviousReplicas = int(prevReplicas)
	}

	if newReplicas, ok := result["new_replicas"].(int32); ok {
		response.NewReplicas = int(newReplicas)
	}

	if action, ok := result["action"].(string); ok {
		response.Action = action
	} else {
		response.Action = "scale"
	}

	if s, ok := result["statefulset"].(string); ok && s != "" {
		response.Statefulset = &s
	}

	// Log successful operation
	r.getAuditLogger().LogMutation(ctx, "scaleStatefulSet", namespace, name, executedBy, true, "")

	return response, nil
}

// Health is the resolver for the health field.
// Refactored to use injected health service
func (r *queryResolver) Health(ctx context.Context) (*model.HealthResponse, error) {
	return r.getHealthService().GetHealth(), nil
}

// Readiness is the resolver for the readiness field.
// Refactored to use injected health service
func (r *queryResolver) Readiness(ctx context.Context) (*model.ReadinessResponse, error) {
	return r.getHealthService().GetReadiness(), nil
}

// Info is the resolver for the info field.
// Refactored to use injected health service
func (r *queryResolver) Info(ctx context.Context) (*model.InfoResponse, error) {
	return r.getHealthService().GetSystemInfo(), nil
}

// Namespaces is the resolver for the namespaces field.
// Refactored with proper error handling and audit logging
func (r *queryResolver) Namespaces(ctx context.Context) (*model.NamespaceListResponse, error) {
	namespaces, err := r.getPodService().ListNamespaces(ctx)
	if err != nil {
		r.getAuditLogger().LogQuery(ctx, "namespaces", "all", 0)
		return nil, r.getErrorHandler().HandleServiceError(err, "listNamespaces")
	}

	// Convert using injected converter
	graphqlNamespaces := make([]*model.NamespaceInfo, len(namespaces))
	for i, ns := range namespaces {
		graphqlNamespaces[i] = r.getConverter().ConvertNamespaceInfo(ns)
	}

	// Log successful query
	r.getAuditLogger().LogQuery(ctx, "namespaces", "all", len(graphqlNamespaces))

	return &model.NamespaceListResponse{
		Count:      len(graphqlNamespaces),
		Namespaces: graphqlNamespaces,
	}, nil
}

// Pods is the resolver for the pods field.
// Refactored with validation and proper error handling
func (r *queryResolver) Pods(ctx context.Context, namespace string) (*model.PodListResponse, error) {
	// Input validation
	if err := r.getValidator().ValidateNamespace(namespace); err != nil {
		r.getAuditLogger().LogQuery(ctx, "pods", namespace, 0)
		return nil, r.getErrorHandler().HandleValidationError(err, "namespace")
	}

	pods, err := r.getPodService().ListPods(ctx, namespace)
	if err != nil {
		r.getAuditLogger().LogQuery(ctx, "pods", namespace, 0)
		return nil, r.getErrorHandler().HandleServiceError(err, "listPods")
	}

	// Convert using injected converter
	graphqlPods := make([]*model.PodInfo, len(pods))
	for i, pod := range pods {
		graphqlPods[i] = r.getConverter().ConvertPodInfo(pod)
	}

	// Log successful query
	r.getAuditLogger().LogQuery(ctx, "pods", namespace, len(graphqlPods))

	return &model.PodListResponse{
		Namespace: namespace,
		Count:     len(graphqlPods),
		Pods:      graphqlPods,
	}, nil
}

// AllPods is the resolver for the allPods field.
// Refactored with optional namespace validation
func (r *queryResolver) AllPods(ctx context.Context, namespace *string) (*model.AllPodsResponse, error) {
	// Validate namespace if provided
	var nsValue string = "all"
	if namespace != nil {
		if err := r.getValidator().ValidateNamespace(*namespace); err != nil {
			r.getAuditLogger().LogQuery(ctx, "allPods", *namespace, 0)
			return nil, r.getErrorHandler().HandleValidationError(err, "namespace")
		}
		nsValue = *namespace
	}

	pods, err := r.getPodService().ListAllPods(ctx, namespace)
	if err != nil {
		r.getAuditLogger().LogQuery(ctx, "allPods", nsValue, 0)
		return nil, r.getErrorHandler().HandleServiceError(err, "listAllPods")
	}

	// Convert using injected converter
	graphqlPods := make([]*model.PodInfo, len(pods))
	for i, pod := range pods {
		graphqlPods[i] = r.getConverter().ConvertPodInfo(pod)
	}

	// Log successful query
	r.getAuditLogger().LogQuery(ctx, "allPods", nsValue, len(graphqlPods))

	return &model.AllPodsResponse{
		Count: len(graphqlPods),
		Pods:  graphqlPods,
	}, nil
}

// Pod is the resolver for the pod field.
// Refactored with validation and error handling
func (r *queryResolver) Pod(ctx context.Context, namespace string, name string) (*model.PodInfo, error) {
	// Input validation
	if err := r.getValidator().ValidateNamespace(namespace); err != nil {
		return nil, r.getErrorHandler().HandleValidationError(err, "namespace")
	}

	if err := r.getValidator().ValidatePodName(name); err != nil {
		return nil, r.getErrorHandler().HandleValidationError(err, "name")
	}

	pod, err := r.getPodService().GetPod(ctx, namespace, name)
	if err != nil {
		return nil, r.getErrorHandler().HandleServiceError(err, "getPod")
	}

	if pod == nil {
		return nil, r.getErrorHandler().HandleNotFoundError("pod", namespace, name)
	}

	return r.getConverter().ConvertPodInfo(*pod), nil
}

// Deployments is the resolver for the deployments field.
// Refactored with validation and converter usage
func (r *queryResolver) Deployments(ctx context.Context, namespace string) (*model.DeploymentListResponse, error) {
	// Input validation
	if err := r.getValidator().ValidateNamespace(namespace); err != nil {
		r.getAuditLogger().LogQuery(ctx, "deployments", namespace, 0)
		return nil, r.getErrorHandler().HandleValidationError(err, "namespace")
	}

	deployments, err := r.getPodService().ListDeployments(ctx, namespace)
	if err != nil {
		r.getAuditLogger().LogQuery(ctx, "deployments", namespace, 0)
		return nil, r.getErrorHandler().HandleServiceError(err, "listDeployments")
	}

	// Convert using injected converter
	graphqlDeployments := make([]*model.DeploymentInfo, len(deployments.Items))
	for i, dep := range deployments.Items {
		graphqlDeployments[i] = r.getConverter().ConvertDeploymentInfo(dep)
	}

	// Log successful query
	r.getAuditLogger().LogQuery(ctx, "deployments", namespace, len(graphqlDeployments))

	return &model.DeploymentListResponse{
		Namespace:   namespace,
		Count:       len(graphqlDeployments),
		Deployments: graphqlDeployments,
	}, nil
}

// Statefulsets is the resolver for the statefulsets field.
// Refactored with validation and converter usage
func (r *queryResolver) Statefulsets(ctx context.Context, namespace string) (*model.StatefulSetListResponse, error) {
	// Input validation
	if err := r.getValidator().ValidateNamespace(namespace); err != nil {
		r.getAuditLogger().LogQuery(ctx, "statefulsets", namespace, 0)
		return nil, r.getErrorHandler().HandleValidationError(err, "namespace")
	}

	statefulsets, err := r.getPodService().ListStatefulSets(ctx, namespace)
	if err != nil {
		r.getAuditLogger().LogQuery(ctx, "statefulsets", namespace, 0)
		return nil, r.getErrorHandler().HandleServiceError(err, "listStatefulSets")
	}

	// Convert using injected converter
	graphqlStatefulSets := make([]*model.StatefulSetInfo, len(statefulsets.Items))
	for i, sts := range statefulsets.Items {
		graphqlStatefulSets[i] = r.getConverter().ConvertStatefulSetInfo(sts)
	}

	// Log successful query
	r.getAuditLogger().LogQuery(ctx, "statefulsets", namespace, len(graphqlStatefulSets))

	return &model.StatefulSetListResponse{
		Namespace:    namespace,
		Count:        len(graphqlStatefulSets),
		Statefulsets: graphqlStatefulSets,
	}, nil
}

// WatchPods is the resolver for the watchPods field.
// Refactored with validation and proper channel management
func (r *subscriptionResolver) WatchPods(ctx context.Context, namespace string) (<-chan *model.PodWatchEvent, error) {
	// Input validation
	if err := r.getValidator().ValidateNamespace(namespace); err != nil {
		r.getAuditLogger().LogSubscription(ctx, "watchPods", namespace, false)
		return nil, r.getErrorHandler().HandleValidationError(err, "namespace")
	}

	// Log subscription start
	r.getAuditLogger().LogSubscription(ctx, "watchPods", namespace, true)

	eventsChan := make(chan *model.PodWatchEvent, 100)
	serviceChan := make(chan services.PodWatchEvent, 100)

	// Start the pod watcher in a goroutine
	go func() {
		defer func() {
			close(eventsChan)
			r.getAuditLogger().LogSubscription(ctx, "watchPods", namespace, false)
		}()

		if err := r.getPodService().WatchPods(ctx, namespace, serviceChan); err != nil {
			// Log error but don't return it through channel
			return
		}
	}()

	// Convert service events to GraphQL events using injected converter
	go func() {
		defer close(serviceChan)
		for event := range serviceChan {
			graphqlEvent := r.getConverter().ConvertPodWatchEvent(event)

			select {
			case eventsChan <- graphqlEvent:
			case <-ctx.Done():
				return
			}
		}
	}()

	return eventsChan, nil
}

// WatchAllPods is the resolver for the watchAllPods field.
// Refactored with proper channel management and audit logging
func (r *subscriptionResolver) WatchAllPods(ctx context.Context) (<-chan *model.PodWatchEvent, error) {
	// Log subscription start
	r.getAuditLogger().LogSubscription(ctx, "watchAllPods", "all", true)

	eventsChan := make(chan *model.PodWatchEvent, 100)
	serviceChan := make(chan services.PodWatchEvent, 100)

	// Start the all pods watcher in a goroutine
	go func() {
		defer func() {
			close(eventsChan)
			r.getAuditLogger().LogSubscription(ctx, "watchAllPods", "all", false)
		}()

		if err := r.getPodService().WatchAllPods(ctx, serviceChan); err != nil {
			// Log error but don't return it through channel
			return
		}
	}()

	// Convert service events to GraphQL events using injected converter
	go func() {
		defer close(serviceChan)
		for event := range serviceChan {
			graphqlEvent := r.getConverter().ConvertPodWatchEvent(event)

			select {
			case eventsChan <- graphqlEvent:
			case <-ctx.Done():
				return
			}
		}
	}()

	return eventsChan, nil
}

// StreamPodLogs is the resolver for the streamPodLogs field.
// Streams pod logs in real-time via GraphQL subscription
func (r *subscriptionResolver) StreamPodLogs(ctx context.Context, namespace string, name string, user *string) (<-chan *model.PodLogLine, error) {
	// Input validation
	if err := r.getValidator().ValidateNamespace(namespace); err != nil {
		r.getAuditLogger().LogSubscription(ctx, "streamPodLogs", namespace, false)
		return nil, r.getErrorHandler().HandleValidationError(err, "namespace")
	}

	if err := r.getValidator().ValidatePodName(name); err != nil {
		r.getAuditLogger().LogSubscription(ctx, "streamPodLogs", namespace, false)
		return nil, r.getErrorHandler().HandleValidationError(err, "name")
	}

	// Build log stream options with sensible defaults
	tailLines := int64(100)
	opts := &services.LogStreamOptions{
		Follow:     true,       // Always follow for streaming
		Timestamps: true,       // Include timestamps
		TailLines:  &tailLines, // Last 100 lines
	}

	// Log subscription start
	r.getAuditLogger().LogSubscription(ctx, "streamPodLogs", namespace+"/"+name, true)

	logsChan := make(chan *model.PodLogLine, 100)
	serviceChan := make(chan services.PodLogLine, 100)

	// Start the log streamer in a goroutine
	go func() {
		defer func() {
			close(logsChan)
			r.getAuditLogger().LogSubscription(ctx, "streamPodLogs", namespace+"/"+name, false)
		}()

		if err := r.getPodService().StreamLogs(ctx, namespace, name, opts, serviceChan); err != nil {
			// Log error but don't return it through channel
			// In a production environment, you might want to send error events
			return
		}
	}()

	// Convert service log lines to GraphQL log lines
	go func() {
		defer close(serviceChan)
		for logLine := range serviceChan {
			graphqlLogLine := r.getConverter().ConvertPodLogLine(logLine)

			select {
			case logsChan <- graphqlLogLine:
			case <-ctx.Done():
				return
			}
		}
	}()

	return logsChan, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
