apiVersion: v1
kind: Service
metadata:
  name: k8s-pod-manager
  namespace: default
  labels:
    app: k8s-pod-manager
spec:
  type: ClusterIP
  selector:
    app: k8s-pod-manager
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-pod-manager-secret
  namespace: default
type: Opaque
stringData:
  database-url: "postgres://postgres:postgres@postgres-service.default.svc.cluster.local:5432/k8s_pod_manager?sslmode=disable"