// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AllPodsResponse struct {
	Count int        `json:"count"`
	Pods  []*PodInfo `json:"pods"`
}

type ContainerInfo struct {
	Name         string `json:"name"`
	Image        string `json:"image"`
	Ready        bool   `json:"ready"`
	RestartCount int    `json:"restartCount"`
	State        string `json:"state"`
}

type DatabaseInfo struct {
	OpenConnections int `json:"openConnections"`
	InUse           int `json:"inUse"`
	Idle            int `json:"idle"`
}

type DeletePodResponse struct {
	Message   string `json:"message"`
	Pod       string `json:"pod"`
	Namespace string `json:"namespace"`
}

type DeploymentInfo struct {
	Name              string      `json:"name"`
	Namespace         string      `json:"namespace"`
	Replicas          int         `json:"replicas"`
	UpdatedReplicas   int         `json:"updatedReplicas"`
	ReadyReplicas     int         `json:"readyReplicas"`
	AvailableReplicas int         `json:"availableReplicas"`
	Labels            []*KeyValue `json:"labels"`
	CreatedAt         time.Time   `json:"createdAt"`
}

type DeploymentListResponse struct {
	Namespace   string            `json:"namespace"`
	Count       int               `json:"count"`
	Deployments []*DeploymentInfo `json:"deployments"`
}

type HealthResponse struct {
	Status    string    `json:"status"`
	Timestamp time.Time `json:"timestamp"`
	Uptime    string    `json:"uptime"`
	Version   string    `json:"version"`
}

type InfoResponse struct {
	Service    *SystemInfo     `json:"service"`
	Kubernetes *KubernetesInfo `json:"kubernetes"`
	Database   *DatabaseInfo   `json:"database"`
	Timestamp  time.Time       `json:"timestamp"`
}

type KeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type KubernetesInfo struct {
	Version  string `json:"version"`
	Platform string `json:"platform"`
}

type Mutation struct {
}

type NamespaceInfo struct {
	Name        string      `json:"name"`
	Status      string      `json:"status"`
	Age         string      `json:"age"`
	Labels      []*KeyValue `json:"labels"`
	Annotations []*KeyValue `json:"annotations"`
}

type NamespaceListResponse struct {
	Count      int              `json:"count"`
	Namespaces []*NamespaceInfo `json:"namespaces"`
}

type PodInfo struct {
	Name           string           `json:"name"`
	Namespace      string           `json:"namespace"`
	Phase          string           `json:"phase"`
	PodIP          *string          `json:"podIP,omitempty"`
	HostIP         *string          `json:"hostIP,omitempty"`
	NodeName       *string          `json:"nodeName,omitempty"`
	Age            string           `json:"age"`
	Ready          string           `json:"ready"`
	Restarts       int              `json:"restarts"`
	Owners         []string         `json:"owners"`
	ControllerType string           `json:"controllerType"`
	Containers     []*ContainerInfo `json:"containers"`
	Labels         []*KeyValue      `json:"labels"`
}

type PodListResponse struct {
	Namespace string     `json:"namespace"`
	Count     int        `json:"count"`
	Pods      []*PodInfo `json:"pods"`
}

type PodWatchEvent struct {
	Type   string   `json:"type"`
	Pod    *PodInfo `json:"pod"`
	Reason *string  `json:"reason,omitempty"`
}

type Query struct {
}

type ReadinessCheck struct {
	Database   string `json:"database"`
	Kubernetes string `json:"kubernetes"`
}

type ReadinessResponse struct {
	Status    string          `json:"status"`
	Checks    *ReadinessCheck `json:"checks"`
	Timestamp time.Time       `json:"timestamp"`
}

type RestartPodResponse struct {
	Message     string  `json:"message"`
	Type        string  `json:"type"`
	Deployment  *string `json:"deployment,omitempty"`
	Statefulset *string `json:"statefulset,omitempty"`
	Controller  *string `json:"controller,omitempty"`
	Pod         string  `json:"pod"`
	Namespace   string  `json:"namespace"`
	Warning     *string `json:"warning,omitempty"`
}

type ScaleInput struct {
	Replicas int `json:"replicas"`
}

type ScaleResponse struct {
	Message          string  `json:"message"`
	Deployment       *string `json:"deployment,omitempty"`
	Statefulset      *string `json:"statefulset,omitempty"`
	Namespace        string  `json:"namespace"`
	PreviousReplicas int     `json:"previousReplicas"`
	NewReplicas      int     `json:"newReplicas"`
	Action           string  `json:"action"`
}

type StatefulSetInfo struct {
	Name            string      `json:"name"`
	Namespace       string      `json:"namespace"`
	Replicas        int         `json:"replicas"`
	ReadyReplicas   int         `json:"readyReplicas"`
	CurrentReplicas int         `json:"currentReplicas"`
	UpdatedReplicas int         `json:"updatedReplicas"`
	Labels          []*KeyValue `json:"labels"`
	CreatedAt       time.Time   `json:"createdAt"`
}

type StatefulSetListResponse struct {
	Namespace    string             `json:"namespace"`
	Count        int                `json:"count"`
	Statefulsets []*StatefulSetInfo `json:"statefulsets"`
}

type Subscription struct {
}

type SystemInfo struct {
	Name    string `json:"name"`
	Version string `json:"version"`
	Uptime  string `json:"uptime"`
}
